theme: jekyll-theme-minimal
title: Yicen的博客
logo: https://avatars.githubusercontent.com/u/55955101?v=4
author: Yicen
excerpt_separator: <!--more-->
paginate: 6
plugins:
  - jekyll-sitemap
  - jekyll-feed
feed:
  path: atom.xml
google_analytics: UA-137710294-1
